name: Build

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]
  workflow_dispatch:

jobs:
  build-i686-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            make
            mingw-w64-i686-toolchain
            mingw-w64-i686-SDL2
            mingw-w64-i686-zlib
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build pd.exe
        run: make -f Makefile -j
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pd-i686-windows
          path: sm64ex/
          retention-days: 0
