name: Build sm64ex for Windows

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install MSYS2
      run: |
        choco install msys2 -y
        refreshenv
        ridk install 1 3 4 5 6
    - name: Set up MSYS2
      run: |
        $env:MSYS2_PATH_TYPE = "inherit"
        $env:MSYS2_ARG_CONV_EXCL = "*"
        $env:MSYS_NO_PATHCONV = 1
        $env:MSYS2_FC_CACHE_SKIP = 1
        $env:MSYS2_FC_CACHE_SIZE = 1
        $env:MSYS2_FC_CACHE_TIMEOUT = 1
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-python3 mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf
    - name: Build sm64ex
      run: |
        make -j$(nproc) WINDOWS_BUILD=1
