name: Build sm64ex for Windows

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSYS2
      run: |
        pacman -Syuu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-python3 mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-mpg123 mingw-w64-x86_64-libpng mingw-w64-x86_64-zlib mingw-w64-x86_64-openssl mingw-w64-x86_64-cmake
        export PATH=$PATH:/mingw64/bin/

    - name: Build sm64ex
      run: |
        make -C build/us_pc -j$(nproc)
