name: Build sm64ex

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MSYS2
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-python3 mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf
    - name: Build sm64ex
      run: |
        make -j$(nproc) EXTERNAL_DATA=1
