name: Build sm64ex

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MSYS2
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo apt-get install libsdl2-dev
        sudo apt install build-essential git python3 libglew-dev
    - name: Build sm64ex
      run: |
        make -j$(nproc) WINDOWS_BUILD=1 EXTERNAL_DATA=1 EXT_OPTIONS_MENU=1 EXT_OPTIONS_MENU=1 TARGET_BITS=64

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sm64ex
        path: /home/runner/work/sm64ex/
